# Generated by Django 3.2.8 on 2021-11-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_reception_payable'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='Reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reception', to='mainpage.reception', verbose_name='پذیرش'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
