# Generated by Django 3.2.8 on 2021-11-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_patientdiagnosis'),
        ('reception', '0002_auto_20211105_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='Reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentReception', to='mainpage.reception', verbose_name='پذیرش'),
        ),
    ]
