# Generated by Django 3.2.8 on 2021-11-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_patientdiagnosis'),
        ('reception', '0003_alter_paymentreceipt_reception'),
    ]

    operations = [
        migrations.CreateModel(
            name='refer_to_surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(verbose_name='تاریخ')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان عمل جراحي')),
                ('name_Doc', models.CharField(max_length=50, verbose_name='نام پزشك معالج')),
                ('patient_history', models.FileField(upload_to='patient_history/')),
                ('Medical_innocence', models.FileField(upload_to='patient_history/')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgerypatuent', to='mainpage.patient', verbose_name='پذیرش')),
            ],
        ),
    ]
