# Generated by Django 3.2.8 on 2021-11-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_auto_20211117_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer_to_surgery',
            name='Medical_innocence',
            field=models.ImageField(upload_to='Medical_innocence/%Y/%m/%d', verbose_name='برائت نامه'),
        ),
        migrations.AlterField(
            model_name='refer_to_surgery',
            name='patient_history',
            field=models.ImageField(upload_to='patient_history/%Y/%m/%d', verbose_name='شرح حال'),
        ),
    ]
