# Generated by Django 3.2.8 on 2021-10-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کلینیک')),
            ],
            options={
                'verbose_name': 'کلینیک',
                'verbose_name_plural': 'کلینیک ها',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NationalCode', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('p_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(max_length=13, verbose_name='تلفن همراه')),
                ('land_line_phone', models.CharField(max_length=13, verbose_name='تلفن ثابت')),
                ('age', models.IntegerField(verbose_name='سن بیمار')),
                ('Gender', models.IntegerField(choices=[(0, 'زن'), (1, 'مرد')], verbose_name='جنسیت')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ServiceCode', models.IntegerField(default=0, verbose_name='کد خدمت')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمت های قابل ارائه',
            },
        ),
        migrations.CreateModel(
            name='Take_Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TurnCode', models.IntegerField(verbose_name='کد وقت')),
                ('FileNumber', models.IntegerField(default=0, verbose_name='شماره پرونده')),
                ('Day', models.IntegerField(choices=[(0, 'شنبه'), (1, ' یک شنبه '), (2, ' دوشنبه '), (3, ' سه شنبه '), (4, ' چهار شنبه '), (5, ' پنجشنبه '), (6, ' جمعه ')], verbose_name='روز')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاريخ ثبت نوبت')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ نوبت')),
                ('TypeTurn', models.IntegerField(blank=True, choices=[(0, 'حضوری'), (1, 'تلفنی'), (2, 'فکس')], null=True, verbose_name='نوع در خواست وقت')),
                ('Description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient1', to='mainpage.patient', verbose_name='پرونده')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='mainpage.clinic', verbose_name='کلینیک')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntranceCode', models.IntegerField(verbose_name='کد پذیرش')),
                ('TurnCode', models.IntegerField(verbose_name='کد وقت')),
                ('FileNumber', models.IntegerField(verbose_name='شماره پرونده')),
                ('EntranceDate', models.DateTimeField(verbose_name='تاریخ پذیرش')),
                ('date', models.DateTimeField(verbose_name='تاریخ نوبت')),
                ('Referrer', models.CharField(max_length=100, verbose_name='معرف')),
                ('Description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient2', to='mainpage.patient', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران پذیرش شده',
            },
        ),
        migrations.CreateModel(
            name='PatientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Reception', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainpage.reception')),
                ('Services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mainpage.services')),
            ],
        ),
    ]
