# Generated by Django 3.2.8 on 2021-10-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.IntegerField(blank=True, choices=[(0, 'زن'), (1, 'مرد')], null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن بیمار'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='land_line_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
    ]
