# Generated by Django 3.2.8 on 2021-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20211031_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take_turn',
            name='date_time',
            field=models.DateTimeField(verbose_name='تاریخ نوبت'),
        ),
    ]
