# Generated by Django 3.2.8 on 2021-11-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_remove_reception_filenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='NationalCode',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
    ]
