# Generated by Django 3.2.8 on 2021-11-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_reception_entrancedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='ServiceCode',
        ),
    ]
