# Generated by Django 3.2.8 on 2021-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_remove_services_servicecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='Payable',
            field=models.IntegerField(default=0, verbose_name='قابل پرداخت'),
        ),
    ]
