# Generated by Django 3.2.8 on 2021-11-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_reception_payable'),
    ]

    operations = [
        migrations.CreateModel(
            name='day_of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات')),
                ('date_time', models.DateTimeField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'روز تعطیل',
                'verbose_name_plural': 'روزهای تعطیل',
            },
        ),
    ]
