# Generated by Django 3.2.8 on 2021-11-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_day_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_of',
            name='date_time',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
