# Generated by Django 3.2.8 on 2021-11-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_alter_day_of_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='TypeTurn',
            field=models.IntegerField(choices=[(0, 'جديد'), (1, 'بعد از عمل'), (2, 'رويت MRA')], default=0, verbose_name='مرحله'),
        ),
    ]
