# Generated by Django 3.2.8 on 2021-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_reception_typeturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.CharField(max_length=200, verbose_name='نام خدمت')),
            ],
            options={
                'verbose_name': 'تشخیص',
                'verbose_name_plural': 'تشخیص',
            },
        ),
    ]
