# Generated by Django 3.2.8 on 2021-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_patientdiagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='Referrer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف'),
        ),
    ]
