# Generated by Django 3.2.10 on 2022-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_alter_reception_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_turn',
            name='part',
            field=models.IntegerField(choices=[(0, 'Post-مغز'), (1, 'post-کمر'), (2, 'post-هیپوفیز'), (3, 'new-مغز'), (4, 'new-کمر'), (5, 'new-هیپوفیز'), (6, 'بخیه-مغز'), (7, 'بخیه-کمر')], default=0, verbose_name='بخش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reception',
            name='TurnCode',
            field=models.CharField(max_length=10, verbose_name='کد وقت'),
        ),
        migrations.AlterField(
            model_name='take_turn',
            name='TurnCode',
            field=models.CharField(max_length=10, verbose_name='کد وقت'),
        ),
    ]
