# Generated by Django 3.2.10 on 2022-02-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_auto_20220205_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take_turn',
            name='clinic',
        ),
    ]
