# Generated by Django 3.2.10 on 2022-02-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0019_remove_take_turn_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_turn',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turn', to=settings.AUTH_USER_MODEL),
        ),
    ]
