# Generated by Django 3.2.10 on 2022-02-14 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0020_take_turn_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take_turn',
            name='Day',
        ),
        migrations.AddField(
            model_name='reception',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to=settings.AUTH_USER_MODEL),
        ),
    ]
