# Generated by Django 3.2.9 on 2022-04-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_auto_20220214_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='TypeTurn',
            field=models.IntegerField(choices=[(0, 'جدید'), (1, 'بعد از عمل'), (2, 'رویت MRA')], default=0, verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='take_turn',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت نوبت'),
        ),
        migrations.AlterField(
            model_name='take_turn',
            name='part',
            field=models.IntegerField(choices=[(0, 'post-مغز'), (1, 'post-کمر'), (2, 'post-هیپوفیز'), (3, 'new-مغز'), (4, 'new-کمر'), (5, 'new-هیپوفیز'), (6, 'بخیه-مغز'), (7, 'بخیه-کمر'), (8, 'post_گردن'), (9, 'new_گردن')], verbose_name='بخش'),
        ),
    ]
